using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using UnityEngine;

///-----------------------------------------------------------------
///   Class:        PhonemeReader.cs
///   Description:  Reads the phonemic information generated by
///                 the text-to-speech engine
///   Author:       Constantinos Charalambous     Date: 28/06/2017
///   Notes:        Phoneme Reader
///-----------------------------------------------------------------

public class PhonemeReader
{
    public List<PhonemeInformation> ReadPhonemeTimings(string file)
    {
        string line;
        List<PhonemeInformation> phonemeInfo = new List<PhonemeInformation>();

        using (StreamReader sr = new StreamReader(file))
        {
            while ((line = sr.ReadLine()) != null)
            {
                string[] lineContents = line.Split();

                PhonemeInformation pi = new PhonemeInformation(float.Parse(lineContents[1]), float.Parse(lineContents[2]), (Phoneme)Enum.Parse(typeof(Phoneme), lineContents[0]))
                {
                    apex = bool.Parse(lineContents[3]),
                    influence = float.Parse(lineContents[4])
                };
                phonemeInfo.Add(pi);
            }
        }

        return phonemeInfo;
    }


}
